export interface CharacterSummary {
  summary: string;
  description: string;
}

export const CHARACTER_SUMMARIES: Record<string, CharacterSummary> = {
  "Alice": {
    summary: "Alice is a character defined by her journey through a world of inherent illogicality. She exhibits a profound sense of self-awareness and philosophical questioning, as evidenced by her internal monologue, \"Who in the world am I? Ah, that's the great puzzle!\" Her attempts to make sense of her surroundings often lead her to recall lessons or moralistic sayings, such as \"Take care of the sense, and the sounds will take care of themselves,\" reflecting a desire to impose order on chaos. She can be observant and critical of others' nonsensical behavior, as she notes, \"A nice muddle their slates'll be in before the trial's over!\"\n\nShe also displays a vivid imagination and a penchant for storytelling, often blurring the lines between what she knows from her own world and the fantastical elements she encounters, like her recollection of \"three little sisters... learning to draw\" who \"lived at the bottom of a well.\" Despite her occasional indignation or strong opinions, such as her family's disdain for \"nasty, low, vulgar things!\" like cats, she remains primarily a curious and adaptable protagonist, navigating bewildering social interactions and physical transformations. Her role is largely that of an innocent but discerning observer whose experiences challenge her understanding of identity, logic, and reality itself.",
    description: "She is the young protagonist who navigates a whimsical, illogical world."
  },
  "Hatter": {
    summary: "Hatter, as revealed through his brief but distinctive dialogue, presents himself as a character deeply, if eccentrically, engaged with the concept of time. His frustration with a clock that \"tells the day of the month, and doesn't tell what o'clock it is!\" immediately establishes him as someone who expects specific functions from objects, yet finds himself confronted with their illogical failings. This quote suggests a mind grappling with order and disorder, highlighting a peculiar sense of logic that is both demanding and perhaps somewhat irrational. He demonstrates a playful, albeit literal, interpretation of language, as seen when he muses about having to \"beat time\" when learning music. This line underscores his tendency to translate idiomatic expressions into concrete actions, revealing a mind that operates on its own peculiar, often nonsensical, terms. He seems to exist in a world where conventional understanding is subtly, yet profoundly, subverted. \n\nHis character, therefore, appears to embody a certain whimsical absurdity, challenging the listener's reliance on common sense and literal meaning. While the provided quotes are limited, they strongly suggest that he serves as a figure who helps establish the surreal and unconventional atmosphere of his world. He is not merely confused by time, but interacts with it in a unique, almost personal, manner, hinting at themes of disrupted reality and the arbitrary nature of rules within the larger narrative. His presence, even through these brief utterances, marks him as a distinct personality, contributing to a landscape where logic bends and language itself can be a source of confusion and amusement.",
    description: "He is an eccentric figure known for his peculiar interpretations of time."
  },
  "Mock Turtle": {
    summary: "The Mock Turtle presents himself as a creature of curious tastes and profound, if understated, philosophy. He demonstrates an appreciation for the whimsical and unconventional, noting his fondness for \"that curious song about the whiting,\" which suggests a delight in the peculiar aspects of his fantastical world. Despite this apparent lightheartedness, he also exhibits a surprising depth regarding the nature of self and time. His assertion that \"it's no use going back to yesterday, because I was a different person then\" encapsulates a belief in constant personal evolution, suggesting an inability or unwillingness to dwell on past selves, and instead embraces the fluidity of identity and the present moment. \n\nHowever, he also displays a somewhat dismissive or perhaps pragmatic view of others' emotional states, as evidenced by his remark, \"It's all his fancy, that: he hasn't got no sorrow, you know. Come on!\" This suggests a desire to move past perceived emotional dramatics or imagined troubles, perhaps urging a more direct engagement with the present. Through his peculiar blend of whimsical enjoyment, philosophical introspection on change, and a slightly impatient pragmatism, he functions as a minor, yet memorable, figure who offers unique perspectives on the themes of identity, time, and the subjective nature of reality within the narrative.",
    description: "He is a whimsical, yet philosophical character who provides unique, sometimes dismissive, insights to the protagonist."
  },
  "Rabbit": {
    summary: "The character, known only as \"rabbit\" from \"Alice's Adventures in Wonderland,\" is presented to the reader without any direct textual evidence through dialogue or narrated actions in the provided excerpts. This complete absence of specific quotes makes a detailed literary analysis of its personality, motivations, or narrative impact impossible to construct based on the given information. Without its own words, or descriptions of its interactions, one cannot ascertain its emotional arc, personal desires, or the specific nature of its relationships with other characters.\n\nConsequently, its relation to the broader themes of \"Alice's Adventures in Wonderland\" also remains unelaborated. Its existence as a 'rabbit' within a fantastical setting might inherently suggest a departure from realism or a symbolic role in Alice's journey, yet these are inferences based solely on the story title and character designation rather than explicit textual support from its dialogue.",
    description: "The rabbit is a non-human character in Alice's Adventures in Wonderland."
  },
  "Bill": {
    summary: "Bill, as presented without any direct quotes, appears to occupy a largely passive or instrumental role within Alice's Adventures in Wonderland. The absence of his own words suggests that he primarily exists to be acted upon by other, more vocal characters, rather than shaping events himself through dialogue or decision. He likely serves as a minor figure, perhaps a bystander or a participant coerced into various fantastical scenarios. This lack of a personal voice implies a subservient position, where his opinions or feelings are not deemed significant enough to be recorded in the given excerpts.\n\nHis relationships, without any quoted interaction, would likely be defined by command and obedience, or by being an object of observation or direction. He seems to possess no discernible emotional arc; rather, his existence appears static, a function of the narrative's more dynamic figures. This suggests that he represents the countless background players in a world governed by arbitrary rules and powerful, capricious personalities.",
    description: "He is a minor character, often coerced into the fantastic scenarios of Wonderland."
  },
  "Dinah": {
    summary: "Dinah, a character from Alice's Adventures in Wonderland, is presented without accompanying quotes, indicating a background or non-speaking role within the narrative. Despite the lack of direct dialogue, her presence is understood as significant through her relationship to the protagonist, Alice. She primarily serves as a tangible link to Alice's reality and home, a comforting anchor from the familiar world that Alice leaves behind upon entering Wonderland. Her continued mention by Alice, even in her absence, highlights Alice's longing for familiarity and the stark contrast between the ordered world she knows and the chaotic, illogical realm she explores.\n\nHer role, while passive, underscores key themes of memory, longing, and the transition from childhood innocence to a bewildering adult-like experience. Dinah embodies the simple, unwavering affection Alice experiences, a stark contrast to the often perplexing and sometimes hostile interactions she encounters with Wonderland's inhabitants. The absence of her by Alice's side reinforces her solitude and vulnerability in a world where logic is inverted and companionship is fleeting. She remains a powerful symbol of home and the grounding influence Alice strives to maintain amidst her surreal adventures.",
    description: "Dinah is Alice's beloved cat, whose absence from Wonderland underscores Alice's displacement from reality."
  },
  "Mouse": {
    summary: "The Mouse, as glimpsed through the singular utterance \"We won't talk about her any more if you'd rather not,\" presents itself as a figure of remarkable politeness and consideration within the whimsical chaos of Alice's Adventures in Wonderland. This brief statement immediately establishes her as a responsive and empathetic conversationalist, one who is attuned to the preferences and potential discomfort of her interlocutor. Her willingness to redirect the conversation indicates a desire to avoid distress or conflict, suggesting a gentle disposition and a social awareness that prioritizes the comfort of others over her own conversational agenda.\n\nGiven the brevity of her recorded dialogue, her role in the broader narrative seems to be that of a minor, perhaps fleeting, but notably courteous presence. Her interaction, though minimal, underscores a theme often present in Wonderland: characters, despite their fantastical nature, often exhibit very human social graces or awkwardnesses.",
    description: "The Mouse serves as a minor, polite conversational participant in the story."
  },
  "Queen": {
    summary: "The queen, as revealed through her pronouncements, appears as an intensely autocratic and impatient figure. She wields absolute power, casually issuing dire ultimatums such as, \"either you or your head must be off, and that in about half no time! Take your choice!\" This chilling declaration immediately establishes her as a ruler whose authority is unquestioned and whose judgments are swift and final, with a clear disregard for due process or the value of life. Her impatience is further highlighted when she delegates responsibility, stating, \"Really, my dear, you must cross-examine the next witness. It quite makes my forehead ache!\"\n\nHer interactions also reveal a desire for control over narrative and information, albeit through arbitrary means. When addressing a point, she dismisses potential objections with, \"Nothing can be clearer than that,\" before abruptly questioning, \"you never had fits, my dear, I think?\" This abrupt shift and leading question suggest a character who dictates terms of truth and seeks to manipulate perceptions. The repeated use of \"my dear\" across different contexts implies a condescending or authoritative tone towards those she addresses, positioning her as a central, dominant force in the immediate interactions.",
    description: "She is a tyrannical and capricious monarch who presides over an illogical court."
  },
  "White Rabbit": {
    summary: "Without specific dialogue quotes provided for the White Rabbit, a detailed analysis of his individual character arc, emotional nuances, or complex relationships cannot be thoroughly constructed. However, from his very name and the context of Alice's Adventures in Wonderland, he is understood to function primarily as an inciting incident for the protagonist. He embodies urgency and the bizarre, with his hurried appearance and exclaimed concerns about lateness prompting Alice's descent into the fantastical world. His significance lies in his initial role as a guide, albeit an unwilling and frantic one, leading Alice away from her mundane reality into the chaotic and illogical realm of Wonderland.",
    description: "The White Rabbit serves as the catalyst for Alice's adventures in Wonderland."
  },
  "Duchess": {
    summary: "The Duchess presents herself as an effusive and opinionated character, immediately expressing intense warmth with a greeting like, \"You can't think how glad I am to see you again, you dear old thing!\" This initial display of affection, however, is quickly contrasted with her strong and somewhat idiosyncratic pronouncements. She holds firm beliefs on seemingly trivial matters, declaring, \"I won't have any pepper in my kitchen at all. Soup does very well without—Maybe it's always pepper that makes people hot-tempered,\" which suggests a unique, perhaps simplistic, philosophy linking external factors to human temperament.\n\nHer discourse frequently veers into didactic or explanatory tangents, as she abruptly delves into scientific facts, stating, \"Just think of what work it would make with the day and night! You see the earth takes twenty-four hours to turn round on its axis—\" This indicates a mind prone to lecturing or sharing information, regardless of immediate relevance. Despite her initial overt affection, she also demonstrates a peculiar self-awareness, anticipating social questions with, \"I dare say you're wondering why I don't put my arm round your waist,\" hinting at either a past of more physical contact or a conscious effort to restrain herself.",
    description: "The Duchess is an eccentric acquaintance encountered by the protagonist."
  },
  "Footman": {
    summary: "The Footman primarily serves as a conduit of communication within the narrative, delivering important messages between key figures. His explicit mention of conveying \"An invitation from the Queen to play croquet\" to \"the Duchess\" clearly establishes his role as a royal messenger, indicating his placement within a structured, albeit peculiar, hierarchy. This function is vital for progressing the plot, as it sets the stage for a subsequent social interaction among the story's eccentric inhabitants.\n\nBeyond his official duties, he offers a brief, yet telling, commentary on his surroundings. His exasperated observation about \"the way all the creatures argue\" and how \"It's enough to drive one crazy!\" reveals his perspective on the pervasive chaos and illogic of the world he inhabits. He appears to be an individual who, despite his subservient role, possesses an awareness of the surrounding pandemonium, finding it not merely whimsical but genuinely taxing to his sanity.",
    description: "The Footman serves as a royal messenger, delivering invitations between the Queen and the Duchess."
  },
  "March Hare": {
    summary: "The March Hare presents himself as a figure whose understanding of the world operates on a distinctly illogical, yet self-assured, plane. His discourse often involves propositions that defy conventional sense, as exemplified when he discusses \"Time\" as a sentient being capable of being influenced through pleasantries rather than force. He believes that \"if you only kept on good terms with him, he'd do almost anything you liked with the clock,\" suggesting a whimsical power dynamic where personal charm overrides objective reality.\n\nFurthermore, he is prone to making statements that, while seemingly profound to him, reveal a distorted grasp of semantics and reasoning. His assertion, \"You might just as well say that 'I see what I eat' is the same thing as 'I eat what I see'!\", illustrates his penchant for false equivalences and verbal gymnastics, which likely serves to disorient or challenge those around him. This challenging nature is also evident in his direct query, \"Do you mean that you think you can find out the answer to it?\", which suggests a tendency to question and perhaps even doubt the intellectual capacities of others.",
    description: "He is a character known for his absurd logic and challenging demeanor within a chaotic social setting."
  },
  "Lory": {
    summary: "Lory emerges as a minor but distinct voice among the creatures Alice encounters early in her Wonderland journey, primarily during the chaotic aftermath of the pool of tears. She is an anthropomorphic bird, characterized by a somewhat pedantic and argumentative demeanor. Her presence is most notable in the nonsensical 'Caucus Race,' where she, alongside other bewildered animals, seeks a solution to dry off. She contributes to the general confusion and playful bickering that defines these initial interactions.\n\nHer primary role in the narrative is to further establish the bizarre and often confrontational social landscape of Wonderland. She engages in brief, almost challenging exchanges, particularly regarding history and age, which serve to underscore the pervasive communication barriers Alice faces. Lory is not presented with an emotional arc; instead, she remains a static element of the fantastical environment.",
    description: "Lory is one of the many animals Alice encounters in Wonderland, participating in the chaotic Caucus Race."
  },
  "William": {
    summary: "William is introduced as an elderly character, notably marked by his \"very white\" hair, yet defined by a remarkably eccentric and persistent habit: he \"incessantly stand[s] on [his] head.\" This peculiar behavior elicits a direct questioning of its appropriateness, as implied by the rhetorical query, \"Do you think, at your age, it is right?\" This suggests William is perceived as someone who defies conventional societal expectations associated with his advanced years.\n\nHis role, though inferred from a single quote, appears to be that of an embodiment of the story's overarching themes of absurdity and the subversion of logic. William's age typically signifies wisdom or a more sedate demeanor, yet his continuous headstands present a stark, whimsical contrast. This defiance of what is considered \"right\" for his age encapsulates the dreamlike, topsy-turvy nature of the world he inhabits.",
    description: "William is an eccentric elderly figure whose unconventional behavior challenges societal expectations within the narrative."
  },
  "Cat": {
    summary: "Based solely on the character's designation as 'cat' within the context of 'Alice's Adventures in Wonderland,' and notably without any provided direct quotes or dialogue, one can infer that it likely embodies an element of the fantastical and whimsical inherent to the Wonderland setting. The absence of specific utterances for the cat makes a precise characterisation challenging; however, its very presence as an animal in a titular 'Adventures' suggests it may serve as an observational figure, an enigmatic guide, or perhaps a source of peculiar encounters for the protagonist.\n\nWithout textual evidence of its interactions or internal thoughts, defining its key relationships or emotional arc is speculative. It might act as a foil, a confidante, or merely another surreal inhabitant of this extraordinary world. Its role in the narrative, based purely on its species, could range from an incidental encounter to a pivotal, albeit silent, influence on Alice's journey.",
    description: "It is an enigmatic animal figure encountered by Alice in Wonderland."
  },
  "Mabel": {
    summary: "Mabel, though never speaking directly within the narrative of Alice's Adventures in Wonderland, functions as a significant conceptual benchmark for Alice during her disorienting transformations. Lacking any personal quotes, her character is defined by Alice's contemplation of her, particularly when Alice fears losing her own identity amidst the chaotic changes in Wonderland. She embodies a perceived \"normal\" or less extraordinary existence that Alice dreads being relegated to.\n\nHer role in the narrative is primarily as a symbolic contrast, highlighting Alice's internal struggle with self-definition and the fluidity of identity. For Alice, the prospect of becoming Mabel represents a regression into a less intelligent or less individual self, emphasizing the protagonist's anxieties about maturation and the potential loss of her unique experiences.",
    description: "Mabel is a childhood acquaintance of Alice, serving as a symbolic contrast to Alice's evolving identity."
  },
  "Mary Ann": {
    summary: "Mary Ann, a character from Alice's Adventures in Wonderland, is presented without any accompanying dialogue or direct textual representation in the provided material. The absence of quotes from her establishes her as a figure whose presence in the narrative, if any, is not conveyed through her own voice or articulated thoughts. This immediately suggests a minor, potentially background, or even entirely off-stage role within the story.\n\nConsequently, any understanding of Mary Ann must emerge from inference rather than direct textual evidence. Her very naming within the fantastical world of Wonderland, a setting known for its vibrant and often verbose inhabitants, might imply a grounding in a more conventional, perhaps domestic, reality.",
    description: "Mary Ann's specific role in the story is undefined by the provided textual evidence."
  },
  "March": {
    summary: "March, as glimpsed through a single whimsical recollection, appears to be a character with a penchant for the peculiar and an imagination untethered by conventional reality. His sole provided quote, \"we went to school in the sea. The master was an old Turtle—we used to call him Tortoise—,\" immediately plunges the reader into a world of delightful absurdity. The plural 'we' suggests March is not a solitary figure but part of an eccentric community that shared this aquatic education.\n\nGiven the brevity of his appearance, March's role in the broader narrative seems to be that of an informant or a source of fantastical anecdotes, rather than a central figure driving the plot. His vivid recall of a 'school in the sea' and an 'old Turtle' for a master positions him as a purveyor of the story's inherent whimsical and illogical themes.",
    description: "March is a minor character known for recounting whimsical anecdotes about his unusual past."
  }
};